---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::jupytext=1.16.0
  - conda-forge::papermill=2.5.0
  - conda-forge::nbconvert=7.16.0
  - conda-forge::pandas=2.2.0
  - conda-forge::seaborn=0.13.2
  - conda-forge::matplotlib=3.8.2
  - conda-forge::numpy=1.26.4
